
all:
	
	@make -f Makefile.payload
	@make -f Makefile.psgroove

usbkey:
	
	@make -f Makefile.payload
	@make -f Makefile.psgroove2

clean:
	@make -f Makefile.payload clean
	@make -f Makefile.psgroove clean

